export const REDIS_PUBLISHER_CLIENT = 'REDIS_PUBLISHER_CLIENT';
export const REDIS_SUBSCRIBER_CLIENT = 'REDIS_SUBSCRIBER_CLIENT';

export const SESSION_MEMBERS_TTL_SECONDS = 120;
export const SESSION_STATE_TTL_SECONDS = 300;
export const EXECUTION_LOCK_TTL_MS = 8000;
